FROM python:3.9

# set work directory
WORKDIR /usr/src/app

# install dependencies
RUN pip install --upgrade pip

# Install the necessary libraries
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .
CMD ["streamlit", "run", "--server.port", "8501", "app.py"]